### ISSUE TITLE
The Translation of New Tab in Navbar - Tiss cool , COOL - Change 

### ISSUE THREAD

**Issue by yogeshu** [CLIxIndia-Dev/clixoer#47]
Coming Soon
- It's updated - 
- check navbar and value on basis of language

**Comment by vighneshmufc** [comment]
Please share the doc of where the translations are

**Comment by DurgaSwetha** [comment]
https://docs.google.com/spreadsheets/d/1FV-kMVlQ2nadFUCbpDvfZqb0KdPWSMDBXK_UwlK12hc/edit#gid=1590687766

**Comment by DurgaSwetha** [comment]
TISS-COOL and COOL-OER in the nav bar have also to be translated...

**Comment by VirajUtekar** [comment]
This issue is been resolved as when selected language from main navigation menu (i.e. English/Hindi/Telugu), the navigation menu options are been translated into selected language

**Screenshot**
![Screenshot from 2021-09-22 13-40-47](https://user-images.githubusercontent.com/90617515/134306839-e4c51109-751f-42a1-80fc-eedb3d5375f5.png)
